/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantMerchantCoin struct {
	Code string `json:"code,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	HasTestNet bool `json:"has_test_net,omitempty"`
	HumanReadableName string `json:"human_readable_name,omitempty"`
	Id string `json:"id,omitempty"`
	// This is a base64 encoded image not an actual url resource
	Image string `json:"image,omitempty"`
	// IsAvailableOnWidget determines if this currency coin is a payment option on our widget
	IsAvailableOnWidget bool `json:"is_available_on_widget,omitempty"`
	IsFiat bool `json:"is_fiat,omitempty"`
	IsStableCoin bool `json:"is_stable_coin,omitempty"`
	Metadata *MerchantMerchantCoinMetadata `json:"metadata,omitempty"`
	Networks []string `json:"networks,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
