/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantMerchantCustomer struct {
	CreatedAt string `json:"created_at,omitempty"`
	Domain string `json:"domain,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Id string `json:"id,omitempty"`
	IsBlacklisted bool `json:"is_blacklisted,omitempty"`
	MerchantId string `json:"merchant_id,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	Reference string `json:"reference,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
