/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantPreferences struct {
	Domain string `json:"domain,omitempty"`
	MerchantId string `json:"merchant_id,omitempty"`
	Settlement *MerchantSettlementPreference `json:"settlement,omitempty"`
	Widget *MerchantWidgetPreference `json:"widget,omitempty"`
}
