/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantPaymentLink struct {
	// Can be zero. If zero, the user has to select the amount to pay
	Amount int32 `json:"amount,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Description string `json:"description,omitempty"`
	Domain string `json:"domain,omitempty"`
	Id string `json:"id,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	IsEnabled bool `json:"is_enabled,omitempty"`
	MerchantId string `json:"merchant_id,omitempty"`
	Metadata *MerchantPaymentLinkMetadata `json:"metadata,omitempty"`
	Title string `json:"title,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
