/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantCoinMetadata struct {
	// XRP addresses must have a destination tag
	DestinationTag int32 `json:"destination_tag,omitempty"`
	// XLM requires a memo
	Memo string `json:"memo,omitempty"`
}
