/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerInitWidgetTransactionRequest struct {
	// Amount. Must be formatte in Kobo. Minimum of 500 Naira
	Amount int32 `json:"amount,omitempty"`
	// Public key only. Never pass your secret key here
	ApiKey string `json:"api_key,omitempty"`
	// Not required. But the customer name. SDK shoudl allow people set this or not
	CustomerName string `json:"customer_name,omitempty"`
	// Customer email. Required
	Email string `json:"email,omitempty"`
	// If coming from a payment page. Put the id of the payment page here. If this is set, it will use the amount from the payment page instead and disregard the amount field in this request
	PaymentLinkId string `json:"payment_link_id,omitempty"`
}
