/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerGenerateCoinRequest struct {
	// Code for the coin you want to generate an address for. e.g (XLM, USDC)
	Code string `json:"code,omitempty"`
	// erc20,trc20,bsc and others
	Network string `json:"network,omitempty"`
}
