/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantWidgetCoin struct {
	Amount int32 `json:"amount,omitempty"`
	Code string `json:"code,omitempty"`
	FiatExchangeRate int32 `json:"fiat_exchange_rate,omitempty"`
	HumanReadableAmount string `json:"human_readable_amount,omitempty"`
	HumanReadableName string `json:"human_readable_name,omitempty"`
	IsStableCoin bool `json:"is_stable_coin,omitempty"`
	Logo string `json:"logo,omitempty"`
	Networks []MerchantWidgetCoinNetwork `json:"networks,omitempty"`
}
