/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantIndustry struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	IndustryName string `json:"industry_name,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
