/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerUpdatePasswordRequest struct {
	ConfirmPassword string `json:"confirm_password,omitempty"`
	CurrentPassword string `json:"current_password,omitempty"`
	NewPassword string `json:"new_password,omitempty"`
}
