/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantMerchantCoin struct {
	Code string `json:"code,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	HasTestNet bool `json:"has_test_net,omitempty"`
	HumanReadableName string `json:"human_readable_name,omitempty"`
	Id string `json:"id,omitempty"`
	// This is a base64 encoded image not an actual url/resource
	Image string `json:"image,omitempty"`
	// IsActive determines whether a coin can be used by any merchant to accept payment via our widget. A merchant can still maintain a balance in such coin. New payments will just be disabled for the said coin This can also be used for fiat currencies that we don't want people to accept money in To also point out, this denotes live mode. If IsActive, it will be accepted in live mode
	IsActive bool `json:"is_active,omitempty"`
	Metadata *MerchantMerchantCoinMetadata `json:"metadata,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
