/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantSettlementPreference struct {
	// who gets the 1% charge, the merchant or the customer if true, the fee will be added to the amount the user wants to pay
	PassFeesToCustomer bool `json:"pass_fees_to_customer,omitempty"`
	// SettleToPaymentCurrency determines how settlement works. If set to true, when a merchant is paid with USDT, the merchant USDT balance will be topped up If set to false, the fiat equivalent will be given to the user
	SettleToPaymentCurrency bool `json:"settle_to_payment_currency,omitempty"`
}
