/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerTransactionStatus struct {
	Amount int32 `json:"amount,omitempty"`
	Coin string `json:"coin,omitempty"`
	Overpaid bool `json:"overpaid,omitempty"`
	PaidInFull bool `json:"paid_in_full,omitempty"`
	Reference string `json:"reference,omitempty"`
	Underpaid bool `json:"underpaid,omitempty"`
}
