/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantApiKey struct {
	CreatedAt string `json:"created_at,omitempty"`
	Domain string `json:"domain,omitempty"`
	Id string `json:"id,omitempty"`
	KeyType int32 `json:"key_type,omitempty"`
	MerchantId string `json:"merchant_id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	Value string `json:"value,omitempty"`
}
