/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantWidgetCoin struct {
	Address string `json:"address,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	Code string `json:"code,omitempty"`
	DestinationTag int32 `json:"destination_tag,omitempty"`
	FiatExchangeRate int32 `json:"fiat_exchange_rate,omitempty"`
	HumanReadableAmount string `json:"human_readable_amount,omitempty"`
	HumanReadableName string `json:"human_readable_name,omitempty"`
	Logo string `json:"logo,omitempty"`
	Memo string `json:"memo,omitempty"`
}
