/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.0
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MerchantMerchantUser struct {
	Country *MerchantCountry `json:"country,omitempty"`
	CountryId string `json:"country_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Id string `json:"id,omitempty"`
	IsEmailVerified bool `json:"is_email_verified,omitempty"`
	Password string `json:"password,omitempty"`
	Roles []MerchantMerchantRole `json:"roles,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
