/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantAddressTransaction struct {
	Amount int32 `json:"amount,omitempty"`
	Coin *MerchantMerchantCoin `json:"coin,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Domain string `json:"domain,omitempty"`
	Hash string `json:"hash,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata *MerchantAddressMetadata `json:"metadata,omitempty"`
	PaymentAddressId string `json:"payment_address_id,omitempty"`
	Reference string `json:"reference,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
