/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantBankPayoutAccount struct {
	AccountName string `json:"account_name,omitempty"`
	AccountNumber string `json:"account_number,omitempty"`
	BankCode string `json:"bank_code,omitempty"`
	BankName string `json:"bank_name,omitempty"`
	Currency string `json:"currency,omitempty"`
	Metadata *MerchantBankPayoutAccountMetadata `json:"metadata,omitempty"`
}
