/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerPagingInfo struct {
	Page int32 `json:"page,omitempty"`
	PerPage int32 `json:"per_page,omitempty"`
	Total int32 `json:"total,omitempty"`
}
