/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerCreateRequestPayout struct {
	// Amount to be sent to the recipient. Please note that this is should be in the currency's lowest denomination. 1,000 Naira would be 100000 while 1 BTC would be 100 million satoshis The currency is automatically retrieved from the payout account
	Amount int32 `json:"amount,omitempty"`
	// The reference of the payout account, PAY_ACCT_XYZ
	Recipient string `json:"recipient,omitempty"`
}
