/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantMerchantCoinMetadata struct {
	// The minimum amount we can take for deposits for this coin NOT implemented
	MinimumDepositAmount int32 `json:"minimum_deposit_amount,omitempty"`
	MinimumPayoutAmount int32 `json:"minimum_payout_amount,omitempty"`
	PayoutFee int32 `json:"payout_fee,omitempty"`
}
