/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantWidgetCoinNetwork struct {
	Address string `json:"address,omitempty"`
	DestinationTag int32 `json:"destination_tag,omitempty"`
	Memo string `json:"memo,omitempty"`
	Name string `json:"name,omitempty"`
}
