/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantPayout struct {
	Amount int32 `json:"amount,omitempty"`
	CoinId string `json:"coin_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Domain string `json:"domain,omitempty"`
	Id string `json:"id,omitempty"`
	MerchantId string `json:"merchant_id,omitempty"`
	Metadata *MerchantPayoutMetadata `json:"metadata,omitempty"`
	Reference string `json:"reference,omitempty"`
	// This will be automatically updated based on payout attempts
	Status int32 `json:"status,omitempty"`
	Type_ int32 `json:"type,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
