/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantMerchantMetadata struct {
	Email string `json:"email,omitempty"`
	LiveWebhookApplicationId string `json:"live_webhook_application_id,omitempty"`
	Plan *MerchantPlan `json:"plan,omitempty"`
	// here for legacy reasons. it is the test app id really
	WebhookApplicationId string `json:"webhook_application_id,omitempty"`
}
