/*
 * Fluidcoins Pay api documentation
 *
 * A suite of APIs to create, manage and accept cryptocurrency payments in Africa
 *
 * API version: 0.1.5
 * Contact: developers@fluidcoins.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerRateData struct {
	// BuyRate is the rate at which we will convert the from currency to the \"to\" currency
	BuyRate int32 `json:"buy_rate,omitempty"`
	From *ServerRateDataFrom `json:"from,omitempty"`
	// Deprecated. please see HumanReadableBuyRate and HumanReadableSaleRate
	HumanReadableAmount float64 `json:"human_readable_amount,omitempty"`
	HumanReadableBuyRate float64 `json:"human_readable_buy_rate,omitempty"`
	HumanReadableSaleRate float64 `json:"human_readable_sale_rate,omitempty"`
	Pair string `json:"pair,omitempty"`
	// Deprecated, please use out BuyRate and SaleRate
	Rate int32 `json:"rate,omitempty"`
	// SaleRate is the rate at which we will convert the \"to\" currency to the \"from\" currency
	SaleRate int32 `json:"sale_rate,omitempty"`
	To *ServerRateDataFrom `json:"to,omitempty"`
}
